version:  "3"

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: password123!
    ports:
      - 1433:1433
    hostname: mssql
    volumes:
      - ./mssql/data/:/var/opt/mssql/data