GO
CREATE PROCEDURE deletePatron (@id INT)
	AS
	BEGIN TRY
		BEGIN TRANSACTION
			DELETE FROM patron WHERE id = @id;
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
GO

EXEC deletePatron @id = 1