GO
CREATE PROCEDURE deleteBook (@id INT)
	AS
	BEGIN TRY
		BEGIN TRANSACTION
			DELETE FROM book WHERE id = @id;
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
GO

EXEC deleteBook @id = 1