GO
CREATE PROCEDURE readBook (@id INT)
	AS
	BEGIN TRY
		BEGIN TRANSACTION
			SELECT * FROM book WHERE id = @id;
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
GO

EXEC readBook @id = 2